// <auto-generated />
using System;
using EnginePerformance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnginePerformance.Migrations
{
    [DbContext(typeof(EngineContext))]
    [Migration("20260128162807_FirstInitialCreate")]
    partial class FirstInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnginePerformance.Model.Engine", b =>
                {
                    b.Property<int>("EngineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EngineId"));

                    b.Property<decimal>("BasePower")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseTorque")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Cylinders")
                        .HasColumnType("int");

                    b.Property<decimal>("Displacement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRPM")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EngineId");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("EnginePerformance.Model.EngineTestParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<double>("ExhaustTemp")
                        .HasColumnType("float");

                    b.Property<double>("FuelConsumption")
                        .HasColumnType("float");

                    b.Property<double>("LoadPercentage")
                        .HasColumnType("float");

                    b.Property<int>("TestRPM")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.ToTable("EngineTestParameters");
                });

            modelBuilder.Entity("EnginePerformance.Model.TurboSelectionResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<decimal>("CalculatedFlow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CalculatedPressure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TurboId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("EngineId");

                    b.HasIndex("TurboId");

                    b.ToTable("TurboSelectionResults");
                });

            modelBuilder.Entity("EnginePerformance.Model.Turbocharger", b =>
                {
                    b.Property<int>("TurboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurboId"));

                    b.Property<decimal>("MaxFlow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PressureRatio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TurboId");

                    b.ToTable("Turbochargers");
                });

            modelBuilder.Entity("EnginePerformance.Model.EngineTestParameter", b =>
                {
                    b.HasOne("EnginePerformance.Model.Engine", "Engine")
                        .WithMany("TestParameters")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("EnginePerformance.Model.TurboSelectionResult", b =>
                {
                    b.HasOne("EnginePerformance.Model.Engine", "Engine")
                        .WithMany("TurboSelectionResults")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnginePerformance.Model.Turbocharger", "Turbocharger")
                        .WithMany("TurboSelectionResults")
                        .HasForeignKey("TurboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");

                    b.Navigation("Turbocharger");
                });

            modelBuilder.Entity("EnginePerformance.Model.Engine", b =>
                {
                    b.Navigation("TestParameters");

                    b.Navigation("TurboSelectionResults");
                });

            modelBuilder.Entity("EnginePerformance.Model.Turbocharger", b =>
                {
                    b.Navigation("TurboSelectionResults");
                });
#pragma warning restore 612, 618
        }
    }
}
